TARGET = symta
INCLUDE = -I ./runtime -I ./runtime/osx
PREFIX =
CC = $(PREFIX)gcc
rt="./runtime/osx/"
CFLAGS = -O2 -Wno-return-type -Wno-pointer-sign $(INCLUDE)
#CFLAGS = -g -O0 -Wno-return-type -Wno-pointer-sign $(INCLUDE)
EXTRA_CFLAGS = 

#-fno-stack-protector

AS = $(CC)
ASFLAGS = $(LOC) -Wall

LD = $(CC) -Wl,-no_pie -Wl,-image_base -Wl,0x100000000 \
           -Wl,-stack_size -Wl,0xA00000
# -Wl,-allow_stack_execute
LDFLAGS = $(LOC)
AR = $(PREFIX)ar
ARFLAGS = rcs

STRIP = $(PREFIX)strip
CP = cp -fp
RM = rm -f

SRCS = main.c gc.c ncm.c bltin.c tokenize.c reader.c meta_table.c ng.c \
       sif.c fs.c sbc.c sif2sbc.c jit.c jit_sbc.c \
       sffi/sffi.c sffi/arch_x64_sysv.c \
       osx/ctx.c osx/compat.c

HDRSB = symta.h common.h ng.h prf.h dh.h ih.h th.h am.h nb.h nh.h fs.h sif.h flt16.h flt16_x86.h meta_table.h sffi/sffi.h jit.h

HDRS = $(addprefix runtime/,$(HDRSB))

OBJS = $(addprefix build/rt/,$(SRCS:.c=.o))
OBJA =

#$(info $$OBJS is [${OBJS}])


all: $(TARGET)

test:
	@echo "hello"

lib/:
	mkdir lib

src/%.h:
	@echo "header \"$@\" is missing"
	@exit -1

# -save-temps=obj

build/rt/ncm.o: runtime/ncm.h

build/rt/gc.o: runtime/gc_types.h

build/rt/osx:
	@mkdir -p build/rt/osx
	@mkdir -p build/rt/sffi

build/rt/%.o: runtime/%.c $(HDRS)
	@echo CC $<
	@$(CC) $(CFLAGS) $(EXTRA_CFLAGS) -c -o $@ $<

$(TARGET): build/rt/osx $(OBJS) $(OBJA)
	@echo LINK $@
	@$(LD) -o $@ $(OBJS) $(OBJA) $(LDFLAGS)

lib/util: lib/ $(OBJS) lib/util.o $(OBJA)
	$(LD) -o $@ $(OBJS) lib/util.o $(OBJA) $(LDFLAGS)

.PHONY: install uninstall clean

clean:
	-$(RM) $(TARGET)
	-$(RM) *.o
	-$(RM) *.exe

