TARGET = lib/ui.ffi

#LOC = -DASMV
#LOC = -DDEBUG -g


PREFIX =
CC = $(PREFIX)gcc
SDL2I = -I./deps/sdl2_mixer/include/SDL2 -I./deps/sdl2/include/SDL2
SDL2L = -L./deps/sdl2/lib  -L./deps/sdl2_mixer/lib
CFLAGS = -DWINDOWS $(LOC) $(DEPS) -O3 -I../../runtime/ $(SDL2I) -I./include -I../gfx/src -DBZ_STRICT_ANSI
EXTRA_CFLAGS = -DNO_VIZ

AS = $(CC)
ASFLAGS = $(LOC) -Wall

LD = $(CC)
LDFLAGS = $(LOC) $(SDL2L) -lsdl2 -lsdl2_mixer

AR = $(PREFIX)ar
ARFLAGS = rcs

STRIP = $(PREFIX)strip
CP = cp -fp
RM = rm -f

SRCS = main.c

OBJS = $(addprefix lib/,$(SRCS:.c=.o))
OBJA =

#$(info $$OBJS is [${OBJS}])


all: $(TARGET)

lib/dummy:
	mkdir -p lib
	echo "dummy" >lib/dummy

lib/%.o: src/%.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) -c -o $@ $<

$(TARGET): lib/dummy $(OBJS) $(OBJA)
	$(LD) -v -fpic -shared -o $@ $(OBJS) $(OBJA) $(LDFLAGS)

.PHONY: install uninstall clean

clean:
	-$(RM) $(TARGET)
	-$(RM) *.o
	-$(RM) *.exe


